export const ADD_YEAR_FILTER_ACTION = "ADD_YEAR_FILTER_ACTION";
export const ADD_GENRES_FILTER_ACTION = "ADD_GENRES_FILTER_ACTION";
export const CHANGE_SORTING_ACTION = "CHANGE_SORTING_ACTION";
export const RESET_FILTER_ACTION = "RESET_FILTER_ACTION";
export const USER_LOG_OUT_ACTION = "USER_LOG_OUT_ACTION";
export const USER_LOG_IN_ACTION = "USER_LOG_IN_ACTION";
